unit TestIdentidadeFiscal.Tipo.CNPJ;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, IdentidadeFiscal.Tipo.CNPJ, Validar.Exceptions, System.SysUtils;

type
  // Test methods for IdentidadeFiscal.Tipo.CNPJ

  TestTCNPJ = class(TTestCase)
  private
    {Private Declarations}
  public
     {Private Declarations}
  published
    procedure TestarCNPJValido;
    procedure TestarCNPJInvalido;
    procedure TestarCNPJ_TamanhoInvalido;
    procedure TestarCNPJ_ApenasLetrasInvalido;
    procedure TestarCNPJ_VazioInvalido;
    procedure TestarCNPJ_RepetidoInvalido;
  end;

implementation

procedure TestTCNPJ.TestarCNPJInvalido;
begin
  CheckException(
  procedure
  begin
   TCNPJ.Create('03204835845344');
  end,
   EArgumentException);
end;

procedure TestTCNPJ.TestarCNPJValido;
begin
   CheckEquals('10667325000186', TCNPJ.Create('10667325000186').Valor);
end;

procedure TestTCNPJ.TestarCNPJ_ApenasLetrasInvalido;
begin
  CheckException(
  procedure
  begin
   TCNPJ.Create('ABCDEFGHIJKLMN');
  end,
   EArgumentException);
end;

procedure TestTCNPJ.TestarCNPJ_TamanhoInvalido;
begin
  CheckException(
  procedure
  begin
   TCNPJ.Create('12345678910111213141516');
  end,
   EArgumentException);
end;

procedure TestTCNPJ.TestarCNPJ_RepetidoInvalido;
begin
  CheckException(
  procedure
  begin
   TCNPJ.Create('11111111111111');
  end,
   EArgumentException);
end;

procedure TestTCNPJ.TestarCNPJ_VazioInvalido;
begin
  CheckException(
  procedure
  begin
   TCNPJ.Create(' ');
  end,
   EArgumentException);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTCNPJ.Suite);
end.

