unit TestVeiculo.Tipo.Placa;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, Veiculo.Tipo.Placa, Validar.Exceptions, System.SysUtils;

type
  // Test methods for Veiculo.Tipo.Placa

  TestTPlaca = class(TTestCase)
  private
    {Private Declarations}
  public
     {Private Declarations}
  published
     procedure TestarPlaca_TamanhoInvalido;
     procedure TestarPlaca_TamanhoValido;
     procedure TestarPlaca_SomenteNumerosInvalido;
     procedure TestarPlaca_SomenteLetrasInvalido;
     procedure TestarPlaca_ClassicaInvalida;
     procedure TestarPlaca_ClassicaValida;
     procedure TestarPlaca_MercosulInvalida;
     procedure TestarPlaca_MercosulValida;

  end;

implementation



{ TestTPlaca }

procedure TestTPlaca.TestarPlaca_ClassicaInvalida;
begin
 CheckException(
 procedure
 begin
  TPlaca.Create('AAA000');
 end,
 EArgumentException);
end;

procedure TestTPlaca.TestarPlaca_ClassicaValida;
begin
  CheckEquals('AAA0000', TPlaca.Create('AAA0000').Valor);
end;

procedure TestTPlaca.TestarPlaca_MercosulInvalida;
begin
   CheckException(
   procedure
   begin
    TPlaca.Create('BRA2E1E');
   end,
   EArgumentException);
end;

procedure TestTPlaca.TestarPlaca_MercosulValida;
begin
  CheckEquals('BRA2E19', TPlaca.Create('BRA2E19').Valor);
end;

procedure TestTPlaca.TestarPlaca_SomenteLetrasInvalido;
begin
   CheckException(
   procedure
   begin
    TPlaca.Create('AAAAAAA');
   end,
   EArgumentException);
end;

procedure TestTPlaca.TestarPlaca_SomenteNumerosInvalido;
begin
   CheckException(
   procedure
   begin
    TPlaca.Create('0000000');
   end,
   EArgumentException);
end;

procedure TestTPlaca.TestarPlaca_TamanhoInvalido;
begin
   CheckException(
   procedure
   begin
    TPlaca.Create('BRA2E1');
   end,
   EArgumentException);
end;

procedure TestTPlaca.TestarPlaca_TamanhoValido;
begin
  TPlaca.Create('BRA2E19');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTPlaca.Suite);
end.

