unit TestEndereco.Tipo.CEP;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, Endereco.Tipo.CEP, Validar.Exceptions, System.SysUtils;

type
  // Test methods for IdentidadeFiscal.Tipo.CNPJ

  TestTCEP = class(TTestCase)
  private
    {Private Declarations}
  public
     {Private Declarations}
  published
    procedure TestarCEP_TamanhoValido;
    procedure TestarCEP_TamanhoInvalido;
    procedure TestarCEP_ValorValido;
    procedure TestarCEP_ValorInvalido;
    procedure TestarCEP_VazioInvalido;
    procedure TestarCEP_RetornoValido;
  end;

implementation


{ TestTCEP }

procedure TestTCEP.TestarCEP_RetornoValido;
begin
  CheckEquals('78098578', TCEP.Create('78098578').Valor);
end;

procedure TestTCEP.TestarCEP_TamanhoInvalido;
begin
  CheckException(
    procedure
    begin
     TCEP.Create('78098578111'); //Tamanho inválido (11<>8)
    end,
   EArgumentException);
end;

procedure TestTCEP.TestarCEP_TamanhoValido;
begin
  TCEP.Create('78098578');
end;

procedure TestTCEP.TestarCEP_ValorInvalido;
begin
  CheckException(
    procedure
    begin
     TCEP.Create('abcdefgh'); //Valor inválido
    end,
   EArgumentException);
end;

procedure TestTCEP.TestarCEP_ValorValido;
begin
   TCEP.Create('57075047');
end;

procedure TestTCEP.TestarCEP_VazioInvalido;
begin
  CheckException(
    procedure
    begin
     TCEP.Create(''); //Vazio valor inválido
    end,
   EArgumentException);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTCEP.Suite);
end.

