unit unit1;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, IdentidadeFiscal.Tipo.CNPJ, Validar.Exceptions;

type
  // Test methods for IdentidadeFiscal.Tipo.CNPJ

  TestTDadosOperacionais = class(TTestCase)
  strict private
    FDadosOperacionais: TCNPJ;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestarTipoOperacaoValido;
    //Enum nasce válido (Teste de verificação)
  end;

implementation

procedure TestTDadosOperacionais.SetUp;
begin
  inherited;
end;

procedure TestTDadosOperacionais.TearDown;
begin

end;

procedure TestTDadosOperacionais.TestarTipoOperacaoValido;
begin
  FDadosOperacionais := TDadosOperacionais.Create(
   opEstadual
  );
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTDadosOperacionais.Suite);
end.

