unit TestValidar.Exceptions;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Rtti, System.SysUtils, System.TypInfo, Validar.Exceptions;

type
  // Test methods for class TValidar

  TestTValidar = class(TTestCase)
  strict private
   {Strict Private Declarations}
  private
   {Private Declarations}
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    //Não deve lancar Execão
    //procedure ValidarLancarErro_NaoLancarExcecao; Sempre lançará uma Exceção!
    //procedure ValidarSeEnumInvalido_NaoLancarExcecao; Enum já nasce válido.
    procedure ValidarSeVazio_NaoLancarExcecao;
    procedure ValidarSeNulo_NaoLancarExcecao;
    procedure ValidarSeMenorQue_NaoLancarExcecao;
    procedure ValidarSeMenorOuZero_Currency_NaoLancarExcecao; //Possui overload
    procedure ValidarSeMenorOuZero_Integer_NaoLancarExcecao; //Possui overload
    procedure ValidarSeMaiorQue_NaoLancarExcecao;
    procedure ValidarSeDiferenteDe_String_NaoLancarExcecao; //Possui overload
    procedure ValidarSeDiferenteDe_Integer_NaoLancarExcecao; //Possui overload
    procedure ValidarSeNaoNumerico_NaoLancarExcecao;
    procedure ValidarSeNaoContemNaListaText_NaoLancarExcecao;

    //Deve Lancar Exceção
    procedure ValidarLancarErro_LancarExcecao;
    //procedure ValidarSeEnumInvalido_LancarExcecao; Enum já nasce válido
    procedure ValidarSeVazio_LancarExcecao;
    procedure ValidarSeNulo_LancarExcecao;
    procedure ValidarSeMenorQue_Currency_LancarExcecao; //Possui overload
    procedure ValidarSeMenorQue_Integer_LancarExcecao; //Possui overload
    procedure ValidarSeMenorQue_LancarExcecao;
    procedure ValidarSeMenorOuZero_Currency_LancarExcecao;
    procedure ValidarSeMaiorQue_LancarExcecao;
    procedure ValidarSeDiferenteDe_String_LancarExcecao; //Possui overload
    procedure ValidarSeDiferenteDe_Integer_LancarExcecao; //Possui overload
    procedure ValidarSeNaoNumerico_LancarExcecao;
    procedure ValidarSeNaoContemNaListaText_LancarExcecao;
  end;

implementation

procedure TestTValidar.SetUp;
begin

end;

procedure TestTValidar.TearDown;
begin

end;

procedure TestTValidar.ValidarLancarErro_LancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.LancarErro('Test', 'Erro Genérico');
  end,
  Exception);
end;

procedure TestTValidar.ValidarSeDiferenteDe_Integer_LancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.SeDiferenteDe('Diferente integer', 0,1);
  end,
  Exception);
end;

procedure TestTValidar.ValidarSeDiferenteDe_Integer_NaoLancarExcecao;
begin
  TValidar.SeDiferenteDe('Diferente Integer', 1,1);
end;

procedure TestTValidar.ValidarSeDiferenteDe_String_LancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.SeDiferenteDe('Diferente string', 'a', 'b');
  end,
  Exception);
end;

procedure TestTValidar.ValidarSeDiferenteDe_String_NaoLancarExcecao;
begin
  TValidar.SeDiferenteDe('Diferente string', 'a', 'a');
end;

procedure TestTValidar.ValidarSeMaiorQue_LancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.SeMaiorQue('Test', 10,9);
  end,
  Exception);
end;

procedure TestTValidar.ValidarSeMaiorQue_NaoLancarExcecao;
begin
  TValidar.SeMaiorQue('Test', 9,10);
end;

procedure TestTValidar.ValidarSeMenorOuZero_Currency_LancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.SeMenorOuZero('Test', -1);
  end,
  Exception);
end;

procedure TestTValidar.ValidarSeMenorOuZero_Currency_NaoLancarExcecao;
begin
  TValidar.SeMenorOuZero('Test', 1);
end;

procedure TestTValidar.ValidarSeMenorOuZero_Integer_NaoLancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.SeMenorOuZero('Test', -1);
  end,
  Exception);
end;

procedure TestTValidar.ValidarSeMenorQue_Currency_LancarExcecao;
begin
  TValidar.SeMenorOuZero('Test', 1);
end;

procedure TestTValidar.ValidarSeMenorQue_Integer_LancarExcecao;
begin

end;

procedure TestTValidar.ValidarSeMenorQue_LancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.SeMenorQue('Test', 9,10);
  end,
  Exception);
end;

procedure TestTValidar.ValidarSeMenorQue_NaoLancarExcecao;
begin
  TValidar.SeMenorQue('Test', 10,9);
end;

procedure TestTValidar.ValidarSeNaoContemNaListaText_LancarExcecao;
 var
 letras: array[0..3] of string;
begin
  letras[0] := 'a';
  letras[1] := 'b';
  letras[2] := 'c';
  letras[3] := 'd';
  CheckException(
  procedure
  begin
  TValidar.SeNaoContemNaListaText('Test', 'e', letras);
  end,
  Exception);
end;

procedure TestTValidar.ValidarSeNaoContemNaListaText_NaoLancarExcecao;
 var
 letras: array[0..3] of string;
begin
  letras[0] := 'a';
  letras[1] := 'b';
  letras[2] := 'c';
  letras[3] := 'd';
  TValidar.SeNaoContemNaListaText('Test', 'a', letras);
end;

procedure TestTValidar.ValidarSeNaoNumerico_LancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.SeNaoNumerico('Test', 'abc123');
  end,
  Exception);
end;

procedure TestTValidar.ValidarSeNaoNumerico_NaoLancarExcecao;
begin
  TValidar.SeNaoNumerico('Test', '123');
end;

procedure TestTValidar.ValidarSeNulo_LancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.SeNulo('Test', nil);
  end,
  Exception);
end;

procedure TestTValidar.ValidarSeNulo_NaoLancarExcecao;
var
 obj : TObject;
begin
  obj := TObject.Create;
  try
    TValidar.SeNulo('Test', obj);
  finally
    obj.Free;
  end;
end;

procedure TestTValidar.ValidarSeVazio_LancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.SeVazio('Test', '');
  end,
  Exception);
end;

procedure TestTValidar.ValidarSeVazio_NaoLancarExcecao;
begin
  TValidar.SeVazio('Test', 'Test');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTValidar.Suite);
end.

