unit TestValidar.Exceptions;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Rtti, System.SysUtils, System.TypInfo, Validar.Exceptions;

type
  // Test methods for class TValidar

  TestTValidar = class(TTestCase)
  strict private
   {Strict Private Declarations}
  private
   {Private Declarations}
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    //Não deve lancar Execão
    //procedure ValidarLancarErro_NaoLancarExcecao; Sempre lançará uma Exceção!
    //procedure ValidarSeEnumInvalido_NaoLancarExcecao; Enum já nasce válido.
    procedure TestarSeVazio_NaoLancarExcecao;
    procedure TestarSeNulo_NaoLancarExcecao;
    procedure TestarSeMenorQue_NaoLancarExcecao;
    procedure TestarSeMenorOuZero_Currency_NaoLancarExcecao; //Possui overload
    procedure TestarSeMenorOuZero_Integer_NaoLancarExcecao; //Possui overload
    procedure TestarSeMaiorQue_NaoLancarExcecao;
    procedure TestarSeDiferenteDe_String_NaoLancarExcecao; //Possui overload
    procedure TestarSeDiferenteDe_Integer_NaoLancarExcecao; //Possui overload
    procedure TestarSeNaoNumerico_NaoLancarExcecao;
    procedure TestarSeNaoContemNaListaText_NaoLancarExcecao;

    //Deve Lancar Exceção
    procedure TestarLancarErro_LancarExcecao;
    //procedure ValidarSeEnumInvalido_LancarExcecao; Enum já nasce válido
    procedure TestarSeVazio_LancarExcecao;
    procedure TestarSeNulo_LancarExcecao;
    procedure TestarSeMenorQue_Currency_LancarExcecao; //Possui overload
    procedure TestarSeMenorQue_Integer_LancarExcecao; //Possui overload
    procedure TestarSeMenorQue_LancarExcecao;
    procedure TestarSeMenorOuZero_Currency_LancarExcecao;
    procedure TestarSeMaiorQue_LancarExcecao;
    procedure TestarSeDiferenteDe_String_LancarExcecao; //Possui overload
    procedure TestarSeDiferenteDe_Integer_LancarExcecao; //Possui overload
    procedure TestarSeNaoNumerico_LancarExcecao;
    procedure TestarSeNaoContemNaListaText_LancarExcecao;
  end;

implementation

procedure TestTValidar.SetUp;
begin

end;

procedure TestTValidar.TearDown;
begin

end;

procedure TestTValidar.TestarLancarErro_LancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.LancarErro('Test', 'Erro Genérico');
  end,
  Exception);
end;

procedure TestTValidar.TestarSeDiferenteDe_Integer_LancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.SeDiferenteDe('Diferente integer', 0,1);
  end,
  Exception);
end;

procedure TestTValidar.TestarSeDiferenteDe_Integer_NaoLancarExcecao;
begin
  TValidar.SeDiferenteDe('Diferente Integer', 1,1);
end;

procedure TestTValidar.TestarSeDiferenteDe_String_LancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.SeDiferenteDe('Diferente string', 'a', 'b');
  end,
  Exception);
end;

procedure TestTValidar.TestarSeDiferenteDe_String_NaoLancarExcecao;
begin
  TValidar.SeDiferenteDe('Diferente string', 'a', 'a');
end;

procedure TestTValidar.TestarSeMaiorQue_LancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.SeMaiorQue('Test', 10,9);
  end,
  Exception);
end;

procedure TestTValidar.TestarSeMaiorQue_NaoLancarExcecao;
begin
  TValidar.SeMaiorQue('Test', 9,10);
end;

procedure TestTValidar.TestarSeMenorOuZero_Currency_LancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.SeMenorOuZero('Test', -1);
  end,
  Exception);
end;

procedure TestTValidar.TestarSeMenorOuZero_Currency_NaoLancarExcecao;
begin
  TValidar.SeMenorOuZero('Test', 1);
end;

procedure TestTValidar.TestarSeMenorOuZero_Integer_NaoLancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.SeMenorOuZero('Test', -1);
  end,
  Exception);
end;

procedure TestTValidar.TestarSeMenorQue_Currency_LancarExcecao;
begin
  TValidar.SeMenorOuZero('Test', 1);
end;

procedure TestTValidar.TestarSeMenorQue_Integer_LancarExcecao;
begin

end;

procedure TestTValidar.TestarSeMenorQue_LancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.SeMenorQue('Test', 9,10);
  end,
  Exception);
end;

procedure TestTValidar.TestarSeMenorQue_NaoLancarExcecao;
begin
  TValidar.SeMenorQue('Test', 10,9);
end;

procedure TestTValidar.TestarSeNaoContemNaListaText_LancarExcecao;
 var
 letras: array[0..3] of string;
begin
  letras[0] := 'a';
  letras[1] := 'b';
  letras[2] := 'c';
  letras[3] := 'd';
  CheckException(
  procedure
  begin
  TValidar.SeNaoContemNaListaText('Test', 'e', letras);
  end,
  Exception);
end;

procedure TestTValidar.TestarSeNaoContemNaListaText_NaoLancarExcecao;
 var
 letras: array[0..3] of string;
begin
  letras[0] := 'a';
  letras[1] := 'b';
  letras[2] := 'c';
  letras[3] := 'd';
  TValidar.SeNaoContemNaListaText('Test', 'a', letras);
end;

procedure TestTValidar.TestarSeNaoNumerico_LancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.SeNaoNumerico('Test', 'abc123');
  end,
  Exception);
end;

procedure TestTValidar.TestarSeNaoNumerico_NaoLancarExcecao;
begin
  TValidar.SeNaoNumerico('Test', '123');
end;

procedure TestTValidar.TestarSeNulo_LancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.SeNulo('Test', nil);
  end,
  Exception);
end;

procedure TestTValidar.TestarSeNulo_NaoLancarExcecao;
var
 obj : TObject;
begin
  obj := TObject.Create;
  try
    TValidar.SeNulo('Test', obj);
  finally
    obj.Free;
  end;
end;

procedure TestTValidar.TestarSeVazio_LancarExcecao;
begin
  CheckException(
  procedure
  begin
  TValidar.SeVazio('Test', '');
  end,
  Exception);
end;

procedure TestTValidar.TestarSeVazio_NaoLancarExcecao;
begin
  TValidar.SeVazio('Test', 'Test');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTValidar.Suite);
end.

