unit TestIdentidadeFiscal.Entidade;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface
 uses
  TestFramework, System.SysUtils, IdentidadeFiscal.Tipo.CNPJ, IdentidadeFiscal.Entidade, Windows;

type
  TestTIdentidadeFiscal = class(TTestCase)
  strict private
    FIdentidadeFiscal: TIdentidadeFiscal;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    //CNPJ
    procedure TestCNPJValido;
    procedure TestCNPJInvalido;

    //Razão Social
    procedure TestRazaoSocialValida;
    procedure TestRazaoSocialInvalida;

    //Inscrição IE
    procedure TestInscricaoIEValida;
    procedure TestInscricaoIEInvalida;

    //Regime Tributário
    //Migração para tipo enum, o estado é tipo válido.
  end;

implementation

{ TestTIdentidadeFiscal }

procedure TestTIdentidadeFiscal.SetUp;
begin
  inherited;
  FIdentidadeFiscal := nil;
end;

procedure TestTIdentidadeFiscal.TearDown;
begin
  FIdentidadeFiscal := nil;
  inherited;
end;

{ ===== CNPJ ===== }

procedure TestTIdentidadeFiscal.TestCNPJValido;
var
  CNPJ: TCNPJ;
begin
    CNPJ := TCNPJ.Create('93771630000140');
    FIdentidadeFiscal := TIdentidadeFiscal.Create(
    CNPJ,
    'Encanadora Real',
    '1234567',
    rtSimplesNacional
  );
    CheckEquals('93771630000140', FIdentidadeFiscal.CNPJ.Valor, 'CNPJ armazenado incorretamente');
end;

procedure TestTIdentidadeFiscal.TestCNPJInvalido;
begin
    CheckException(
    procedure
    var
    CNPJ: TCNPJ;
    begin
      CNPJ := TCNPJ.Create('123'); //inválido
      FIdentidadeFiscal := TIdentidadeFiscal.Create(
      CNPJ,
      'Encanadora Real',
      '1234567',
      rtSimplesNacional
      );
    end,
    Exception,
    'CNPJ inválido não lançou exceção'
  );
end;

{ ===== Razão Social ===== }

procedure TestTIdentidadeFiscal.TestRazaoSocialValida;
var
  CNPJ: TCNPJ;
begin
    CNPJ := TCNPJ.Create('93771630000140');
    FIdentidadeFiscal := TIdentidadeFiscal.Create(
    CNPJ,
    'Empresa Válida',
    '1234567',
    rtSimplesNacional
  );
    CheckEquals('Empresa Válida', FIdentidadeFiscal.RazaoSocial);
end;

procedure TestTIdentidadeFiscal.TestRazaoSocialInvalida;
var
  CNPJ: TCNPJ;
begin
    CNPJ := TCNPJ.Create('93771630000140');
    CheckException(
    procedure
    begin
      FIdentidadeFiscal := TIdentidadeFiscal.Create(
      CNPJ,
      '', //inválido
      '1234567',
      rtSimplesNacional
      );
    end,
      Exception,
      'Razão Social inválida não lançou exceção'
  );
end;

{ ===== Inscrição IE ===== }

procedure TestTIdentidadeFiscal.TestInscricaoIEValida;
var
  CNPJ: TCNPJ;
begin
    CNPJ := TCNPJ.Create('93771630000140');
    FIdentidadeFiscal := TIdentidadeFiscal.Create(
    CNPJ,
    'Empresa Válida',
    '1234567',
    rtSimplesNacional
  );
    CheckEquals('1234567', FIdentidadeFiscal.InscricaoIE);
end;

procedure TestTIdentidadeFiscal.TestInscricaoIEInvalida;
var
  CNPJ: TCNPJ;
begin
    CNPJ := TCNPJ.Create('93771630000140');
    CheckException(
    procedure
    begin
      FIdentidadeFiscal := TIdentidadeFiscal.Create(
      CNPJ,
      'Empresa Válida',
      '', //inválido
      rtSimplesNacional
      );
    end,
    Exception,
    'Inscrição IE inválida não lançou exceção'
  );
end;

initialization
  RegisterTest(TestTIdentidadeFiscal.Suite);

end.


