unit TestEndereco;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Endereco.Entidade, Endereco.Tipo.CEP, System.SysUtils;

type
  // Test methods for class TEndereco

  TestTEndereco = class(TTestCase)
  strict private
    FEndereco: TEndereco;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestValidarEstadoUFValido;
    procedure TestValidarEstadoUFInvalido;
  end;

implementation

{ TestTEndereco }

procedure TestTEndereco.SetUp;
begin
  inherited;

end;

procedure TestTEndereco.TearDown;
begin
  inherited;

end;

procedure TestTEndereco.TestValidarEstadoUFInvalido;
var
  CEP: TCEP;
begin
  CEP := TCEP.Create('68500000');
    begin
      TEndereco.Create(
        CEP,
        '123',         // Numero Inválido
        '2704302',     // IBGE válido
        'Maceio',      // Município válido
        'Centro',      // Bairro válido
        'Rua A',       // Logradouro válido
        '',
        'AL'           // UF Válido
      );
    end;
end;

procedure TestTEndereco.TestValidarEstadoUFValido;
var
  CEP: TCEP;
begin
  CEP := TCEP.Create('57000000'); // ajuste conforme sua classe

  CheckNotNull(
    TEndereco.Create(
      CEP,
      '123',
      '2704302',
      'Alagoas',
      'Centro',
      'Rua A',
      '',
      'AL'
    )
  );
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTEndereco.Suite);
end.

