unit TestVeiculo.Entidade;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Veiculo.Tipo.Placa, Veiculo.Entidade, System.SysUtils,
  Validar.Exceptions;

type
  // Test methods for class TVeiculo

  TestTVeiculo = class(TTestCase)
  strict private
    FVeiculo: TVeiculo;
    FPlaca  : TPlaca;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestPlacaUFValida;
    procedure TestPlacaUFInvalida;
    procedure TestTipoVeiculoValido;
    procedure TestTipoVeiculoInvalido;
    procedure TestProprietarioValido;
    procedure TestProprietarioInvalido;
    procedure TestMarcaValido;
    procedure TestMarcaInvalido;
    procedure TestModeloValido;
    procedure TestModeloInvalido;
    procedure TestCorValido;
    procedure TestCorInvalido;
    procedure TestCapacidadeKgValido;
    procedure TestCapacidadeKgInvalido;
    procedure TestKmAtualValido;
    procedure TestKmAtualInvalido;
    procedure TestRastreadorValido;
    procedure TestRastreadorInvalido;
    procedure TestRastreador_FalseVazio_Valido;
    procedure TestRastreador_TrueVazio_Invalido;
  end;

implementation

procedure TestTVeiculo.SetUp;
begin
 FPlaca := TPlaca.Create('AAA0000');
end;

procedure TestTVeiculo.TearDown;
begin
  FVeiculo.Free;
  FVeiculo := nil;
end;
 {
  FPlaca            := APlaca;
  FPlacaUF          := APlacaUf;
  FTipoVeiculo      := ATipoVeiculo;
  FProprietario     := AProprietario;
  FMarca            := AMarca;
  FModelo           := AModelo;
  FCor              := ACor;
  FCapacidadeKg     := ACapacidadeKg;
  FKmAtual          := AKmAtual;
  FRastreador       := ARastreador;
  FNumeroRastreador := ANumeroRastreador;

 }
procedure TestTVeiculo.TestCapacidadeKgInvalido;
begin
  CheckException(
   procedure
   begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC',
   'Caminhão',
   'Cargo',
   'Marca',
   'Modelo',
   'Prata',
   0,
   25000,
   true,
   'A99AA'
   );
   end,
   Exception);
end;

procedure TestTVeiculo.TestCapacidadeKgValido;
begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC',
   'Caminhão',
   'Cargo',
   'Marca',
   'Modelo',
   'Prata',
   1000,
   25000,
   true,
   'A99AA'
   );
end;

procedure TestTVeiculo.TestCorInvalido;
begin
  CheckException(
   procedure
   begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC',
   'Caminhão',
   'Cargo',
   'Marca',
   'Modelo',
   'Grafite metálico profundo Especial',
   1000,
   25000,
   true,
   'A99AA'
   );
   end,
   Exception);
end;

procedure TestTVeiculo.TestCorValido;
begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC',
   'Caminhão',
   'Cargo',
   'Marca',
   'Modelo',
   'Grafite metálico',
   1000,
   25000,
   true,
   'A99AA'
   );
end;

procedure TestTVeiculo.TestKmAtualInvalido;
begin
  CheckException(
   procedure
   begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC',
   'Caminhão',
   'Cargo',
   'Marca',
   'Modelo',
   'Grafite metálico',
   1000,
   -1,
   true,
   'A99AA'
   );
   end,
   Exception);
end;

procedure TestTVeiculo.TestKmAtualValido;
begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC',
   'Caminhão',
   'Cargo',
   'Marca',
   'Modelo',
   'Grafite metálico',
   1000,
   25000,
   true,
   'A99AA'
   );
end;

procedure TestTVeiculo.TestMarcaInvalido;
begin
  CheckException(
   procedure
   begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC',
   'Caminhão',
   'Cargo',
   'Titan Estradas Motores de Carga Max',
   'Modelo',
   'Grafite metálico',
   1000,
   25000,
   true,
   'A99AA'
   );
   end,
   Exception);
end;

procedure TestTVeiculo.TestMarcaValido;
begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC',
   'Caminhão',
   'Cargo',
   'Marca',
   'Modelo',
   'Grafite metálico',
   1000,
   25000,
   true,
   'A99AA'
   );
end;

procedure TestTVeiculo.TestModeloInvalido;
begin
  CheckException(
   procedure
   begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC',
   'Caminhão',
   'Cargo',
   'Marca',
   'Modelo TitanRoad X900 Turbo Diesel Long Haul Edition',
   'Grafite metálico',
   1000,
   25000,
   true,
   'A99AA'
   );
   end,
   Exception);
end;

procedure TestTVeiculo.TestModeloValido;
begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC',
   'Caminhão',
   'Cargo',
   'Marca',
   'Modelo',
   'Grafite metálico',
   1000,
   25000,
   true,
   'A99AA'
   );
end;

procedure TestTVeiculo.TestPlacaUFInvalida;
begin
  CheckException(
   procedure
   begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   '', //Inválido UF
   'Caminhão',
   'Cargo',
   'Marca',
   'Modelo',
   'Grafite metálico',
   1000,
   25000,
   true,
   'A99AA'
   );
   end,
   Exception);
end;

procedure TestTVeiculo.TestPlacaUFValida;
begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC', //Válido UF
   'Caminhão',
   'Cargo',
   'Marca',
   'Modelo',
   'Grafite metálico',
   1000,
   25000,
   true,
   'A99AA'
   );
end;

procedure TestTVeiculo.TestProprietarioInvalido;
begin
  CheckException(
   procedure
   begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC',
   'Caminhão',
   '', //Inválido Proprietario
   'Marca',
   'Modelo',
   'Grafite metálico',
   1000,
   25000,
   true,
   'A99AA'
   );
   end,
   Exception);
end;

procedure TestTVeiculo.TestProprietarioValido;
begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC',
   'Caminhão',
   'Cargo', //Válido Proprietario
   'Marca',
   'Modelo',
   'Grafite metálico',
   1000,
   25000,
   true,
   'A99AA'
   );
end;

procedure TestTVeiculo.TestRastreadorInvalido;
begin
  CheckException(
   procedure
   begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC',
   'Caminhão',
   'Cargo',
   'Marca',
   'Modelo',
   'Grafite metálico',
   1000,
   25000,
   false, //Inválido Rastreador
   'A99AA'
   );
   end,
   Exception);
end;

procedure TestTVeiculo.TestRastreadorValido;
begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC',
   'Caminhão',
   'Cargo',
   'Marca',
   'Modelo',
   'Grafite metálico',
   1000,
   25000,
   True, //Válido Rastreador
   'A99AA'
   );
end;


procedure TestTVeiculo.TestRastreador_FalseVazio_Valido;
begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC',
   'Caminhão',
   'Cargo',
   'Marca',
   'Modelo',
   'Grafite metálico',
   1000,
   25000,
   false, //Válido Rastreador
   ''    //Válido Vazio 'Se não há Rastreador não há identificador'
   );
end;

procedure TestTVeiculo.TestRastreador_TrueVazio_Invalido;
begin
  CheckException(
   procedure
   begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC',
   'Caminhão',
   'Cargo',
   'Marca',
   'Modelo',
   'Grafite metálico',
   1000,
   25000,
   True, //Inválido Se há um Rastreador deve haver um identificador
   ''
   );
   end,
   Exception);
end;

procedure TestTVeiculo.TestTipoVeiculoInvalido;
begin
  CheckException(
   procedure
   begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC',
   '', //Inválido 'Tipo de Veiculo Ausente'
   'Cargo',
   'Marca',
   'Modelo',
   'Grafite metálico',
   1000,
   25000,
   True,
   'A99AA'
   );
   end,
   Exception);
end;

procedure TestTVeiculo.TestTipoVeiculoValido;
begin
   FVeiculo := TVeiculo.Create(
   FPlaca,
   'SC',
   'Caminhão', //Válido'
   'Cargo',
   'Marca',
   'Modelo',
   'Grafite metálico',
   1000,
   25000,
   True,
   'A99AA'
   );
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTVeiculo.Suite);
end.

