unit TestSistemaOperacional.Entidade;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, SistemaOperacional.Entidade, Validar.Exceptions, System.SysUtils;

type
  // Test methods for class TSistemaOperacional

  TestTSistemaOperacional = class(TTestCase)
  strict private
    FSistemaOperacional: TSistemaOperacional;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestarResponsavelValido;
    procedure TestarResponsavelInvalido_Ausente;
    procedure TestarResponsavelInvalido_Limite;
  end;

implementation

procedure TestTSistemaOperacional.SetUp;
begin
 inherited
end;

procedure TestTSistemaOperacional.TearDown;
begin
  FSistemaOperacional.Free;
  FSistemaOperacional := nil;
end;

procedure TestTSistemaOperacional.TestarResponsavelInvalido_Ausente;
begin
  CheckException(
  procedure
   begin
    FSistemaOperacional := TSistemaOperacional.Create(
    saAtivo,
    ''
    );
   end,
 Exception);
end;

procedure TestTSistemaOperacional.TestarResponsavelInvalido_Limite;
begin
  CheckException(
  procedure
   begin
    FSistemaOperacional := TSistemaOperacional.Create(
    saAtivo,
    'Aurélio Venturini da Costa e Silva Montenegro Albuquerqueira'
    );
   end,
 Exception);
end;

procedure TestTSistemaOperacional.TestarResponsavelValido;
begin
   FSistemaOperacional := TSistemaOperacional.Create(
   saAtivo,
   'Aurélio Venturini');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTSistemaOperacional.Suite);
end.

