unit TestDadosFiscais.Entidade;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, DadosFiscais.Entidade, System.SysUtils, Validar.Exceptions;

type
  // Test methods for class TDadosFiscais

  TestTDadosFiscais = class(TTestCase)
  strict private
    FDadosFiscais: TDadosFiscais;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestarObservacaoFiscalValido;
    procedure TestarObservacaoFiscalInvalido;
    procedure TestarAliquotaPadraoPrecoValido;
    procedure TestarAliquotaPadraoPrecoInvalido;
    procedure TestarAliquotaPadraoDiferenteTributacao;

  end;

implementation

{ TestTDadosFiscais }

{
=== ORDEM CORRETA ===
  Papel Ct-e
  Tipo de Tributacao
  Observação Fiscal
  Aliquota padrão
}

procedure TestTDadosFiscais.SetUp;
begin
  inherited;

end;

procedure TestTDadosFiscais.TearDown;
begin
  FDadosFiscais.Free;
  inherited;
end;

procedure TestTDadosFiscais.TestarAliquotaPadraoDiferenteTributacao;
begin
  CheckException(
  procedure
  begin
  FDadosFiscais := TDadosFiscais.Create(
   pcEmitente,
   ttIsento,
   'Sem Observação',
   55.99);
  end,
  Exception);
end;

procedure TestTDadosFiscais.TestarAliquotaPadraoPrecoInvalido;
begin
  CheckException(
  procedure
  begin
  FDadosFiscais := TDadosFiscais.Create(
   pcEmitente,
   ttNormal,
   'Sem Observação',
   -1);
  end,
  Exception);
end;

procedure TestTDadosFiscais.TestarAliquotaPadraoPrecoValido;
begin
  FDadosFiscais := TDadosFiscais.Create(
   pcEmitente,
   ttNormal,
   'Sem Observação',
   55.99);
  CheckNotNull(FDadosFiscais);
end;

procedure TestTDadosFiscais.TestarObservacaoFiscalInvalido;
begin
  CheckException(
  procedure
  begin
  FDadosFiscais := TDadosFiscais.Create(
   pcEmitente,
   ttNormal,
   'Impostos e taxas incidentes sobre o CT-e seguem a legislação vigente,' +
   ' podendo variar conforme a operação, origem, destino e enquadramento fiscal do contribuinte.' +
   ' Valores destacados possuem natureza tributária e atendem às normas aplicáveis ao transporte.', //Excede o limite de 250 Caracteres
   50.99);
  end,
  Exception);
end;

procedure TestTDadosFiscais.TestarObservacaoFiscalValido;
begin
  FDadosFiscais := TDadosFiscais.Create(
   pcEmitente,
   ttNormal,
   'Sem Observação', //Limite de Caracteres 250
   55.99);
  CheckNotNull(FDadosFiscais);
end;


initialization
  // Register any test cases with the test runner
  RegisterTest(TestTDadosFiscais.Suite);
end.

