unit TestEndereco;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Endereco.Entidade, Endereco.Tipo.CEP, System.SysUtils;

type
  // Test methods for class TEndereco

  TestTEndereco = class(TTestCase)
  strict private
    FEndereco: TEndereco;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestarEstadoValido;
    procedure TestarEstadoInvalido;
    procedure TestarCepValido;
    procedure TestarCepInvalido;
    procedure TestarMunicipioValido;
    procedure TestarMunicipioInvalido;
    procedure TestarBairroValido;
    procedure TestarBairroInvalido;
    procedure TestarLogradouroValido;
    procedure TestarLogradouroInvalido;
    procedure TestarNumeroValido;
    procedure TestarNumeroInvalido;
    procedure TestarCodigoIBGEValido;
    procedure TestarCodigoIBGEInvalido;
    procedure TestarComplementoValido;
    procedure TestarComplementoInvalido;
  end;

implementation

{ TestTEndereco }
{   === ORDEM CORRETA ===
  CEP
  EstadoUF
  Municipio
  Bairro
  Logradouro
  Numero
  CodigoIBGE
  Complemento
}


procedure TestTEndereco.SetUp;
begin
  inherited;

end;

procedure TestTEndereco.TearDown;
begin
  inherited;

end;


procedure TestTEndereco.TestarEstadoValido;
var
  CEP: TCEP;
begin
  CEP       := TCEP.Create('12345678');
  FEndereco := TEndereco.Create(
   CEP,
   'SP',
   'São Paulo',
   'São Bento',
   'Avenida Paulista',
   '123',
   '3550308',
   'Sala 10'
   );
  CheckNotNull(FEndereco);
end;

procedure TestTEndereco.TestarEstadoInvalido;
var
  CEP: TCEP;
begin
  CEP := TCEP.Create('12345678');
  CheckException(
    procedure
    begin
      TEndereco.Create(
       CEP,
       '',
       'São Paulo',
       'São Bento',
       'Avenida Paulista',
       '123',
       '3550308',
       'Sala 10'
      );
    end,
    Exception);
end;


procedure TestTEndereco.TestarCepValido;
var
  CEP: TCEP;
begin
  CEP       := TCEP.Create('12345678');
  FEndereco := TEndereco.Create(
   CEP,
   'SP',
   'São Paulo',
   'São Bento',
   'Avenida Paulista',
   '123',
   '3550308',
   'Sala 10'
   );
  CheckNotNull(FEndereco);
end;

procedure TestTEndereco.TestarCepInvalido;
begin
  CheckException(
    procedure
    var
      CEP: TCEP;
    begin
      CEP := TCEP.Create('123'); // falha no record
      TEndereco.Create(
       CEP,
       'SP',
       'São Paulo',
       'São Bento',
       'Avenida Paulista',
       '123',
       '3550308',
       'Sala 10'
      );
    end,
    Exception);
end;

procedure TestTEndereco.TestarMunicipioValido;
var
  CEP: TCEP;
begin
  CEP       := TCEP.Create('12345678');
  FEndereco := TEndereco.Create(
   CEP,
   'SP',
   'São Paulo',
   'São Bento',
   'Avenida Paulista',
   '123',
   '3550308',
   'Sala 10'
  );
  CheckNotNull(FEndereco);
end;

procedure TestTEndereco.TestarMunicipioInvalido;
var
  CEP: TCEP;
begin
  CEP := TCEP.Create('12345678');

  CheckException(
    procedure
    begin
      TEndereco.Create(
       CEP,
       'SP',
       '',
       'São Bento',
       'Avenida Paulista',
       '123',
       '3550308',
       'Sala 10'
      );
    end,
    Exception);
end;

procedure TestTEndereco.TestarBairroValido;
var
  CEP: TCEP;
begin
  CEP       := TCEP.Create('12345678');
  FEndereco := TEndereco.Create(
   CEP,
   'SP',
   'São Paulo',
   'São Bento',
   'Avenida Paulista',
   '123',
   '3550308',
   'Sala 10'
   );
  CheckNotNull(FEndereco);
end;

procedure TestTEndereco.TestarBairroInvalido;
var
  CEP: TCEP;
begin
  CEP := TCEP.Create('12345678');

  CheckException(
    procedure
    begin
      TEndereco.Create(
       CEP,
       'SP',
       'São Paulo',
       '',
       'Avenida Paulista',
       '123',
       '3550308',
       'Sala 10'
      );
    end,
    Exception);
end;

procedure TestTEndereco.TestarLogradouroValido;
var
  CEP: TCEP;
begin
  CEP       := TCEP.Create('12345678');
  FEndereco := TEndereco.Create(
   CEP,
   'SP',
   'São Paulo',
   'São Bento',
   'Avenida Paulista',
   '123',
   '3550308',
   'Sala 10'
   );
  CheckNotNull(FEndereco);
end;

procedure TestTEndereco.TestarLogradouroInvalido;
var
  CEP: TCEP;
begin
  CEP := TCEP.Create('12345678');
  CheckException(
    procedure
    begin
      TEndereco.Create(
       CEP,
       'SP',
       'São Paulo',
       'São Bento',
       '',
       '123',
       '3550308',
       'Sala 10'
      );
    end,
    Exception);
end;

procedure TestTEndereco.TestarNumeroValido;
var
  CEP: TCEP;
begin
  CEP       := TCEP.Create('12345678');
  FEndereco := TEndereco.Create(
   CEP,
   'SP',
   'São Paulo',
   'São Bento',
   'Avenida Paulista',
   '123',
   '3550308',
   'Sala 10'
   );
  CheckNotNull(FEndereco);
end;

procedure TestTEndereco.TestarNumeroInvalido;
var
  CEP: TCEP;
begin
  CEP := TCEP.Create('12345678');
  CheckException(
    procedure
    begin
      TEndereco.Create(
       CEP,
       'SP',
       'São Paulo',
       'São Bento',
       'Avenida Paulista',
       '',
       '3550308',
       'Sala 10'
      );
    end,
    Exception);
end;

procedure TestTEndereco.TestarCodigoIBGEValido;
var
  CEP: TCEP;
begin
  CEP       := TCEP.Create('12345678');
  FEndereco := TEndereco.Create(
   CEP,
   'SP',
   'São Paulo',
   'São Bento',
   'Avenida Paulista',
   '123',
   '3550308',
   'Sala 10'
  );
  CheckNotNull(FEndereco);
end;

procedure TestTEndereco.TestarCodigoIBGEInvalido;
var
  CEP: TCEP;
begin
  CEP := TCEP.Create('12345678');
  CheckException(
    procedure
    begin
      TEndereco.Create(
       CEP,
       'SP',
       'São Paulo',
       'São Bento',
       'Avenida Paulista',
       '123',
       '',
       'Sala 10'
    );
    end,
    Exception);
end;

procedure TestTEndereco.TestarComplementoValido;
var
  CEP: TCEP;
begin
  CEP       := TCEP.Create('12345678');
  FEndereco := TEndereco.Create(
   CEP,
   'SP',
   'São Paulo',
   'São Bento',
   'Avenida Paulista',
   '123',
   '3550308',
   'Sala 10'
   );
  CheckNotNull(FEndereco);
end;

procedure TestTEndereco.TestarComplementoInvalido;
var
  CEP: TCEP;
begin
  CEP := TCEP.Create('12345678');
  CheckException(
    procedure
    begin
      TEndereco.Create(
       CEP,
       'SP',
       'São Paulo',
       'São Bento',
       'Avenida Paulista',
       '123',
       '3550308',
       ''
      );
    end,
    Exception);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTEndereco.Suite);
end.

